---
group: person_overview
sub_group: pregnancy_status
fields:
  - template: "Status: {pregnancy_status}"
    relevance: "pregnancy_status != ''"

---
sub_group: hiv_details
fields:
  - template: "Testing done before?: {is_previously_tested_hiv}"
    relevance: "is_previously_tested_hiv != ''"

  - template: "Prev. test results: {previous_hiv_status}"
    relevance: "previous_hiv_status != ''"

  - template: "Current results: {hiv_status}"
    relevance: "hiv_status != ''"
    isRedFont: "hiv_status == 'positive' || hiv_status == 'Positive'"

---
sub_group: current_visit
fields:
  - template: "Visit Type: {visit_type}"
    relevance: "visit_type != ''"

  - template: "Scheduled?: {previous_appointment}"
    relevance: "previous_appointment != ''"

  - template: "Appt. due date: {date_of_appointment}"
    relevance: "date_of_appointment != ''"