jdk:
  - openjdk17

install:
  # Build and publish the library to JitPack's local Maven so consumers can resolve it; skip sample and signing
  - ./gradlew -x test -x lint -PskipSample=true -PskipSigning=true :opensrp-opd:publishMavenPublicationToMavenLocal --no-daemon --stacktrace
