jdk:
  - openjdk17

install:
  # Build only the library module; skip configuring/building :sample
  - ./gradlew -x test -PskipSample=true :opensrp-opd:assembleRelease :opensrp-opd:publishToMavenLocal --no-daemon --stacktrace
